### ISSUE TITLE
How to use tblis to improve TDOT?

### ISSUE THREAD

**Issue by Lancashire3000** [dgasmith/opt_einsum#180] opened 2021-12-31 04:52 UTC
I am not sure if this question fits there.

Inspired by this thread https://stackoverflow.com/questions/67116825/what-is-tdot-subroutine-in-blas
it seems `TDOT` is to swap indices of tensor, to let the dummy indices together. And `tblis` could skip this kind of permutation. 
I tried to use `tblis` as a backend of `opt-einsum` to test the performance. I am not sure about my setting. More specifically, should I set `use_blas = False`?

For the following two types of contractions, 
```
'xyf,xtf,ytpf,fr->tpr'
'bdik,acaj,ikab,ajac,ikbd->'
```
it seems to me that `use_blas = False` can either accelerate or slow down the performance. 

Here are my code and results
```
# based on https://optimized-einsum.readthedocs.io/en/stable/path_finding.html#examining-the-path
# and https://optimized-einsum.readthedocs.io/en/stable/greedy_path.html?highlight=tdot


import opt_einsum as oe
import time
import scipy.stats
from pyscf import tblis_einsum
import numpy as np


from opt_einsum.backends.dispatch import _cached_funcs
_cached_funcs['einsum', 'numpy'] = tblis_einsum.contract


def mean_confidence_interval(data, var_name, unit, confidence=0.95):
    a = 1.0 * np.array(data)
    n = len(a)
    m, se = np.mean(a), scipy.stats.sem(a)
    h = se * scipy.stats.t.ppf((1 + confidence) / 2., n-1)
    
    print(var_name, round(m, 5), "\u00B1",  round(h, 5), unit )

print('test tdot')
contraction = 'xyf,xtf,ytpf,fr->tpr'

M = np.random.rand(35, 37, 59)
A = np.random.rand(35, 51, 59)
B = np.random.rand(37, 51, 51, 59)
C = np.random.rand(59, 27)

path, path_info = oe.contract_path(contraction, M, A, B, C)
print('tdot',path_info)

path, path_info = oe.contract_path(contraction, M, A, B, C, use_blas = False)
print('tdot',path_info)


n_times = 64

list_time = []
einsum_string = 'xyf,xtf,ytpf,fr->tpr'
for i in range(n_times):
    start_time = time.time()
    contract_result = oe.contract(einsum_string, M,A,B,C, use_blas = False)
    finish_time = time.time()
    list_time.append(finish_time - start_time)

mean_confidence_interval(list_time, 'blas false', 's' )



list_time = []

for i in range(n_times):
    start_time = time.time()
    contract_result = oe.contract(einsum_string, M,A,B,C, use_blas = True)
    finish_time = time.time()
    list_time.append(finish_time - start_time)

mean_confidence_interval(list_time, 'blas true', 's' )



contraction = 'bdik,acaj,ikab,ajac,ikbd->'

einsum_string = 'bdik,acaj,ikab,ajac,ikbd->'

# Build random views to represent this contraction
unique_inds = set(einsum_string) - {',', '-', '>'}
index_size = [10, 17, 9, 10, 13, 16, 15, 14, 12]
sizes_dict = dict(zip(unique_inds, index_size))
views = oe.helpers.build_views(einsum_string, sizes_dict)

print('type',type(views))


path, path_info = oe.contract_path(einsum_string, *views)
print(path_info)

path, path_info = oe.contract_path(einsum_string, *views, use_blas = False)
print(path_info)

list_time = []

for i in range(n_times):
    start_time = time.time()
    contract_result = oe.contract(einsum_string, *views, use_blas = False)
    finish_time = time.time()
    list_time.append(finish_time - start_time)

mean_confidence_interval(list_time, 'blas false', 's' )

list_time = []

for i in range(n_times):
    start_time = time.time()
    contract_result = oe.contract(einsum_string, *views)
    finish_time = time.time()
    list_time.append(finish_time - start_time)

mean_confidence_interval(list_time, 'blas true', 's' )
```

For the first one, the contraction information 
```

  Complete contraction:  xyf,xtf,ytpf,fr->tpr
         Naive scaling:  6
     Optimized scaling:  4
      Naive FLOP count:  2.146e+10
  Optimized FLOP count:  2.744e+7
   Theoretical speedup:  7.823e+2
  Largest intermediate:  1.535e+5 elements
--------------------------------------------------------------------------------
scaling        BLAS                current                             remaining
--------------------------------------------------------------------------------
   4              0           xtf,xyf->tfy                      ytpf,fr,tfy->tpr
   4              0          tfy,ytpf->tfp                           fr,tfp->tpr
   4           TDOT            tfp,fr->tpr                              tpr->tpr
tdot   Complete contraction:  xyf,xtf,ytpf,fr->tpr
         Naive scaling:  6
     Optimized scaling:  4
      Naive FLOP count:  2.146e+10
  Optimized FLOP count:  2.744e+7
   Theoretical speedup:  7.823e+2
  Largest intermediate:  1.535e+5 elements
--------------------------------------------------------------------------------
scaling        BLAS                current                             remaining
--------------------------------------------------------------------------------
   4              0           xtf,xyf->tfy                      ytpf,fr,tfy->tpr
   4              0          tfy,ytpf->tfp                           fr,tfp->tpr
   4              0            tfp,fr->tpr                              tpr->tpr
blas false 0.03608 ± 0.00239 s
blas true 0.02424 ± 0.00094 s
type <class 'list'>
  Complete contraction:  bdik,acaj,ikab,ajac,ikbd->
         Naive scaling:  7
     Optimized scaling:  4
      Naive FLOP count:  2.387e+8
  Optimized FLOP count:  8.442e+4
   Theoretical speedup:  2.827e+3
  Largest intermediate:  1.440e+3 elements
```
suggests `use_blas = False` will turn off `TDOT`. But the timing is

```
blas false 0.03608 ± 0.00239 s
blas true 0.02424 ± 0.00094 s
```
the second one 
```
blas false 0.00163 ± 0.00014 s
blas true 0.00176 ± 0.00014 s
```
which is the opposite.  Should I try larger dimensional arrays for better testing the timing?

**Comment by jcmgray** [comment] 2022-01-08 23:33
I can't seem to get tblis to install in order to investigate but here are some thoughts:

1. Just to be clear, `use_blas=False` means call `einsum` for every contraction, not just those that *have* to be done be `einsum`. So `use_blas=False` is the correct choice to use tblis only. `use_blas=True` will mix `tblis_contract` and `numpy.tensordot`
2. tblis is probably faster than `numpy.einsum`, (as much as anything due to being multi-threading) - the question is whether you want to replace just this (the BLAS=0 contractions) or tensordot as well? For just the first you might want to call `_cached_funcs['einsum', 'tblis'] = tblis_einsum.contract` so you can compare `contract(......, backend='tblis', use_blas=False)` separately
3. for blassable contractions tblis might not be faster than tensordot, which relies on matrix multiplication - one of the most heavily optimized algorithms ever. It might use less memory due to the lack of transposing however (certainly on GPU this is a key reason to use e.g. `cutensor`)
4.  optimizing pairwise contractions is very hard to do generically - one has to conside ordering of indices, strides, number of dimensions etc (see for example https://docs.nvidia.com/cuda/cutensor/user_guide.html#). 

Which is all to say, you probably need to benchmark (einsum+tensordot vs tblis+tensordot vs tblis+tblis) with the actual contractions and sizes you are interested in - there will be no universally 'better' choice,

**Comment by dgasmith** [comment] 2022-01-15 18:03
I recommend performing a microbenchmark to demonstrate where TBLIS really shines:
```python
dim = 200
arr1 = np.random.rand(dim, dim, dim, dim)
arr2 = np.random.rand(dim, dim, dim, dim)

# Performance should be nearly identical
opt_einsum.contract("abcd,cdef->abef", arr1, arr2)
tblis_einsum.contract("abcd,cdef->abef", arr1, arr2)

# TBLIS should be much faster
opt_einsum.contract("acbd,cdef->abef", arr1, arr2)
tblis_einsum.contract("acbd,cdef->abef", arr1, arr2)
```

In the first example the "zip" index `cd` is already aligned in memory meaning we can directly call GEMM which TBLIS is rough equal to. In the second example the zip index is not memory aligned meaning before we call GEMM we need to call a memory copy/transpose which is quite slow due to memory performance (literally drag a block from memory, do a few L1 cache moves, ship it back to memory) and then the GEMM. TBLIS will pull a small block from memory, transpose the block in L1/2 cache, perform matrix multiplication, and ship back to memory.

I don't know how PySCF implemented their TBLIS connection, it also looks like they may mix einsum and TBLIS where appropriate.

**Comment by Lancashire3000** [comment] 2022-02-21 02:26
> I recommend performing a microbenchmark to demonstrate where TBLIS really shines:
> 
> ```python
> dim = 200
> arr1 = np.random.rand(dim, dim, dim, dim)
> arr2 = np.random.rand(dim, dim, dim, dim)
> 
> # Performance should be nearly identical
> opt_einsum.contract("abcd,cdef->abef", arr1, arr2)
> tblis_einsum.contract("abcd,cdef->abef", arr1, arr2)
> 
> # TBLIS should be much faster
> opt_einsum.contract("acbd,cdef->abef", arr1, arr2)
> tblis_einsum.contract("acbd,cdef->abef", arr1, arr2)
> ```
> 
> In the first example the "zip" index `cd` is already aligned in memory meaning we can directly call GEMM which TBLIS is rough equal to. In the second example the zip index is not memory aligned meaning before we call GEMM we need to call a memory copy/transpose which is quite slow due to memory performance (literally drag a block from memory, do a few L1 cache moves, ship it back to memory) and then the GEMM. TBLIS will pull a small block from memory, transpose the block in L1/2 cache, perform matrix multiplication, and ship back to memory skipping the temporary copy and lowering memory movement.
> 
> I don't know how PySCF implemented their TBLIS connection, it also looks like they may mix einsum and TBLIS where appropriate.

I apologive for my late reply. I tested `"abcd,cdef->abef"` and `"acbd,cdef->abef"` with smaller dimension (`n=60`) and more time run statistics (`32 times 95% confidence interval`). The results are, labels follow as the four contractions up to down
```
oe-1 3.87943 ± 0.26033 s
tblis-1 3.93798 ± 0.03104 s
oe-2 4.84126 ± 0.08545 s
tblis-2 5.23336 ± 0.04422 s
```
I will ask `PySCF` developers on this issue. My stupid code is below

```
import opt_einsum as oe
import time
import scipy.stats
from pyscf import tblis_einsum
import numpy as np


def mean_confidence_interval(data, var_name, unit, confidence=0.95):
    a = 1.0 * np.array(data)
    n = len(a)
    m, se = np.mean(a), scipy.stats.sem(a)
    h = se * scipy.stats.t.ppf((1 + confidence) / 2., n-1)
    
    print(var_name, round(m, 5), "\u00B1",  round(h, 5), unit )


n_times = 32

dim = 60
arr1 = np.random.rand(dim, dim, dim, dim)
arr2 = np.random.rand(dim, dim, dim, dim)

# Performance should be nearly identical
list_time = []
for i in range(n_times):
    start = time.time()
    oe.contract("abcd,cdef->abef", arr1, arr2)
    end = time.time()
    list_time.append(end - start)
mean_confidence_interval(list_time, 'oe-1', 's' )


list_time = []
for i in range(n_times):
    start = time.time()
    tblis_einsum.contract("abcd,cdef->abef", arr1, arr2)
    end = time.time()
    list_time.append(end - start)
mean_confidence_interval(list_time, 'tblis-1', 's' )

# TBLIS should be much faster
list_time = []
for i in range(n_times):
    start = time.time()
    oe.contract("acbd,cdef->abef", arr1, arr2)
    end = time.time()
    list_time.append(end - start)
mean_confidence_interval(list_time, 'oe-2', 's' )

list_time = []
for i in range(n_times):
    start = time.time()
    tblis_einsum.contract("acbd,cdef->abef", arr1, arr2)
    end = time.time()
    list_time.append(end - start)
mean_confidence_interval(list_time, 'tblis-2', 's' )
```

**Comment by dgasmith** [comment] 2022-02-21 19:15
This is not expected, can we try one more contraction which tests dual copies?
`acbd,cedf->abef`

**Comment by Lancashire3000** [comment] 2022-02-21 23:16
With previous examples
```
oe-1 3.65289 ± 0.09114 s
tblis-1 4.007 ± 0.08987 s
oe-2 3.91824 ± 0.1254 s
tblis-2 4.06633 ± 0.05253 s
oe-3 4.04502 ± 0.04259 s
tblis-3 4.18279 ± 0.20722 s
```
I ran the tests on my local PC. I tried not to open other programs. But it may happen that timing depends on the condition of the PC during the test.

Here is the python code. I could have built a function to take the contraction and *arr as the input...
```
import opt_einsum as oe
import time
import scipy.stats
from pyscf import tblis_einsum
import numpy as np


def mean_confidence_interval(data, var_name, unit, confidence=0.95):
    a = 1.0 * np.array(data)
    n = len(a)
    m, se = np.mean(a), scipy.stats.sem(a)
    h = se * scipy.stats.t.ppf((1 + confidence) / 2., n-1)
    
    print(var_name, round(m, 5), "\u00B1",  round(h, 5), unit )


n_times = 32

dim = 60
arr1 = np.random.rand(dim, dim, dim, dim)
arr2 = np.random.rand(dim, dim, dim, dim)

# Performance should be nearly identical
list_time = []
for i in range(n_times):
    start = time.time()
    oe.contract("abcd,cdef->abef", arr1, arr2)
    end = time.time()
    list_time.append(end - start)
mean_confidence_interval(list_time, 'oe-1', 's' )


list_time = []
for i in range(n_times):
    start = time.time()
    tblis_einsum.contract("abcd,cdef->abef", arr1, arr2)
    end = time.time()
    list_time.append(end - start)
mean_confidence_interval(list_time, 'tblis-1', 's' )

# TBLIS should be much faster
list_time = []
for i in range(n_times):
    start = time.time()
    oe.contract("acbd,cdef->abef", arr1, arr2)
    end = time.time()
    list_time.append(end - start)
mean_confidence_interval(list_time, 'oe-2', 's' )

list_time = []
for i in range(n_times):
    start = time.time()
    tblis_einsum.contract("acbd,cdef->abef", arr1, arr2)
    end = time.time()
    list_time.append(end - start)
mean_confidence_interval(list_time, 'tblis-2', 's' )




list_time = []
for i in range(n_times):
    start = time.time()
    oe.contract("acbd,cedf->abef", arr1, arr2)
    end = time.time()
    list_time.append(end - start)
mean_confidence_interval(list_time, 'oe-3', 's' )

list_time = []
for i in range(n_times):
    start = time.time()
    tblis_einsum.contract("acbd,cedf->abef", arr1, arr2)
    end = time.time()
    list_time.append(end - start)
mean_confidence_interval(list_time, 'tblis-3', 's' )
```

**Comment by h-larsson** [comment] 2022-02-23 01:01
I can confirm this using an older version of pyscf on 3 different computers with 1 thread(!). 

```
Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz
oe-1 1.97051 ± 0.01055 s
tblis-1 2.12913 ± 0.05277 s
oe-2 1.96468 ± 0.00754 s
tblis-2 2.14967 ± 0.05688 s
oe-3 1.94343 ± 0.00127 s
tblis-3 2.05263 ± 0.004 s
```
```
Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz 
oe-1 1.40233 ± 0.02955 s
tblis-1 1.63868 ± 0.03135 s
oe-2 1.42817 ± 0.02844 s
tblis-2 1.64649 ± 0.0323 s
oe-3 1.4556 ± 0.02981 s
tblis-3 1.63513 ± 0.02596 s
```
```
Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
oe-1 2.06735 ± 0.06872 s
tblis-1 2.35737 ± 0.02365 s
oe-2 2.12891 ± 0.05165 s
tblis-2 2.43197 ± 0.04357 s
oe-3 2.17573 ± 0.02488 s
tblis-3 2.38283 ± 0.01953 s
```

**Comment by dgasmith** [comment] 2022-02-27 03:40
Hopefully PySCF will get back to you as that isn't an expected outcome and could be their implementation. I believe we should close this and move the primary discussion to PySCF.

**Closed** 2022-02-27 17:18 UTC
